version: '3.0'

services:
    fastdfs:
        build: .
        image: fastdfs:5.11
        restart: always
        container_name: fastdfs
        environment:
            - WEB_PORT=8888
            - IP=192.168.14.174
        volumes:
            - ${HOME}/docker-data/fdfs:/var/local/fdfs
        privileged: true
        network_mode: "host"